#!/bin/bash
for i in `seq 5 5 430`
do head -c $(($i*1000)) text > tmpfile
echo "$" >> tmpfile
memory=`./create tmpfile | grep Memory | awk '{print $2}'`
let "memory = memory / 1000000"
echo $memory
echo "Graph memory for creating file with $i kB: $memory"
echo "$i $memory" >> results/graph
done
