#!/bin/bash
for i in `seq 5 5 430`
do head -c $(($i*1000)) text > tmpfile
echo "$" >> tmpfile
./create tmpfile
size=`ls -s | head -n1 | awk '{print $2}' | sed 's/M//g'`
let "size = size - 1872"
size=`echo "scale=2;$size / 1000" | bc`
#echo "Time for creating file with $i kB: $exectime seconds"
echo "Size für file with $i kB: $size kB"
echo "$i $size" >> results/graph
#echo "$i $exectime" >> results/graph
done
