#!/bin/bash
for y in `seq 5`
    do
for i in `seq 5 5 470`
    do head -c $(($i*1000)) samples/cantrbry/plrabn12.txt > samples/tmpfile
    echo "$" >> samples/tmpfile
    output=`./create samples/tmpfile`
    
    exectime=`echo "$output" | grep graph | awk '{print $7}'`

    size=`ls -s files | head -n1 | awk '{print $2}' | sed 's/M//g'`
    #let "size = size - 1536"
    size=`echo "scale=2;$size / 1000" | bc`
    outputtime=`echo "$output"  | grep output | awk '{print $5}'`
    echo "Time for creating the graph for $i kB: $exectime seconds"
    echo "Size for  $i kB: $size MB"
    echo "Ouput time for $i kB: $outputtime seconds"
    echo "$i $size" >> results/outputsize
    echo "$i $exectime" >> results/exectime
    echo "$i $outputtime" >> results/uploadtime
    rm files/*
done
done
