#!/bin/bash
for y in `seq 5`
do
for i in `seq 5 5 470`
do head -c $(($i*1000)) samples/cantrbry/plrabn12.txt > samples/tmpfile
echo "$" >> samples/tmpfile
memory=`./create samples/tmpfile`
echo "Graph memory for creating file with $i kB: $memory"
echo "$i $memory" >> results/memory_graph
done
done
