#!/bin/bash
i=`./search "$1"| grep -v INFO`
occurs=`echo $i | wc -w`
if [ $occurs -eq 1 ]; then
	numoccurs=0	
else 
	numoccurs=`echo $i | awk {'print $1'}`
fi
realnumoccurs=`grep -o "$1" $2 | wc -l`
if [ $numoccurs == "false"  ];  then
    if [ $realnumoccurs -eq 0 ]; then
        echo "Check for $1 valid"
    else
        echo "Check for $1 Failed. Got $numoccurs expected 0"
    fi
else
    if [ $numoccurs -eq $realnumoccurs ]; then
	    echo "Check for $1 Valid"
    else
	    echo "Check for $1 Failed. Got $numoccurs expected $realnumoccurs"
    fi
fi

