package sse.Backend;

import java.io.IOException;
import java.io.InputStream;
import java.io.RandomAccessFile;

import sse.IOHandler.BinaryOut;
import sse.IOHandler.SecurityEngine;

public interface Backend {

	/**
	 * This method opens a new file and returns the new output stream. It has to
	 * close the previous stream.
	 * 
	 * @param currentBlock
	 *            : the current block the writer is writing to
	 * @param w
	 *            the current output stream
	 * @param secEngine
	 *            the current encryption engine
	 * @return the new output stream
	 */
	public BinaryOut openNextFile(long currentBlock, BinaryOut w,
			SecurityEngine secEngine);

	/**
	 * This method deletes any unneeded files and closes all streams.
	 * 
	 * @param currentBlock
	 *            : the current block
	 * @param w
	 *            : the current output stream
	 * @param secEngine
	 *            : the current security engine
	 */
	public void finalize(long currentBlock, BinaryOut w,
			SecurityEngine secEngine);

	/**
	 * This method opens the next file for searching and returns whether we have
	 * reached an end or not. It also has to save the new stream in a manner
	 * that getStream() can return it.
	 * 
	 * @param block
	 *            : the block to open
	 * @param fileName
	 *            : the file to open
	 * @param position
	 *            : the position to jump to
	 * @param oldBlock
	 *            : the old block to delete
	 * @param stream
	 *            : the current stream
	 * @param sEn
	 *            : the current security engine
	 * @return whether the end is reached or not
	 * @throws IOException
	 */
	public boolean searchNext(long block, String fileName, long position,
			long oldBlock, RandomAccessFile stream, SecurityEngine sEn)
			throws IOException;

	/**
	 * This method returns the new stream generated by searchNext();
	 * 
	 * @return new stream to read from
	 */
	public RandomAccessFile getStream();

	/**
	 * This method returns a stream to the block containing the meta
	 * information.
	 * 
	 * @return a stream to the first block.
	 */
	public InputStream loadStartBlock();

}
